---
  - name: Installation mysql
    become: yes
    apt: name={{item}} update_cache=yes
    with_items:
      - python-mysqldb
      - python-pymysql
      - mysql-server
    
  
  - name: lancer mysql
    service:
     name: mysqld
     state: started
    become: yes
     
  - name: Creation d'un utilisateur avec tous les privilèges
    mysql_user:
      name: invite
      password: 12345
      priv: '*.*:All'
      state: present
    become: yes